version: 2
jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: circleci/ruby:2.3-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: rails_api-react_client
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: rails_api-react_client
          POSTGRES_DB: rails_api-react_client_production
    steps:
      - checkout

      - type: cache-restore
        name: Restore bundle cache
        key: myapp-bundle-{{ checksum "Gemfile.lock" }}

      # - type: cache-restore
      #   name: Restore yarn cache
      #   key: myapp-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Bundle Install
          command: bin/bundle install --path vendor/bundle

      # - run:
      #     name: Yarn Install
      #     command: yarn install

      - type: cache-save
        name: Store bundle cache
        key: myapp-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # - type: cache-save
      #   name: Store yarn cache
      #   key: myapp-yarn-{{ checksum "yarn.lock" }}
      #   paths:
      #     - ~/.yarn-cache

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

     - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
